### ISSUE TITLE
Message d'erreur à l'installation : manifest.inc.php manquant

### ISSUE THREAD

**Issue by LeoBoudet** [YunoHost-Apps/matomo_ynh#10]
Selon l'installateur c'est normal qu'il soit manquant dans le cas d'une installation depuis git...
J'ai un doute alors je laisse ici l'info. Le message d'erreur apparaît à la première étape d'installation (contrôle d'intégrité).

**Comment by mrtpcet** [comment]
same issue

**Comment by Brouilles** [comment]
Same.

**Comment by ericgaspar** [comment]
Please reopen if this is still an issue
