### ISSUE TITLE
Aucun message reçu par mail à l'installation

### ISSUE THREAD

**Issue by LeoBoudet** [YunoHost-Apps/matomo_ynh#11]
Il est dit dans la doc qu'un mail contenant les identifiants mysql sera envoyé à l'administrateur au moment de l'installation de Matomo mais je ne reçois rien.

**Comment by biphasic** [comment]
hello,
I also didn't receive an email. It does create the db though. Just try 'matomo' for user, db and pw after the installation is done and you have the matomo setup screen in front of you. If it cannot connect, try resetting the mysql user password for matomo user manually.

**Comment by LeoBoudet** [comment]
It didn't work, I had to recreate the password of the matomo user.

**Comment by Brouilles** [comment]
Same.

**Comment by Brouilles** [comment]
How I can proceed? If I try to access to mysql with `mysql` or with my user. I get the following error: `ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: NO)` (similar with my account, but password; TRUE).

**Comment by biphasic** [comment]
here is the query btw: SET PASSWORD FOR 'matomo'@'localhost' = PASSWORD('matomo');

**Comment by rt4mn** [comment]
I also didn't receive an email, stuck on "Database Setup" screen.

> It didn't work, I had to recreate the password of the matomo user.
> here is the query btw: SET PASSWORD FOR 'matomo'@'localhost' = PASSWORD('matomo');

How, exactly, did you do this?

**Comment by ericgaspar** [comment]
Please reopen if this is still an issue

**Comment by krichtof** [comment]
It's still an issue for me.

**Comment by ericgaspar** [comment]
Did you [set up an email clients](https://yunohost.org/en/administrate/overview/emails) to receive those emails:
`root@yourdomain.ltd`
`admin@yourdomain.ltd` 

The easiest way to receive admin emails is to install Roundcube as it comes preconfigured.

**Comment by krichtof** [comment]
I receive emails as root@mydomain.tld from other applications installed on my yunohost instance.
But no mail from matomo with credentials for the database

**Comment by ericgaspar** [comment]
If you can test, I have reworked the send-mail script. The mail should land to [root@mydomain.tld](mailto:root@mydomain.tld).

```
sudo yunohost app install https://github.com/YunoHost-Apps/matomo_ynh/tree/send-mail
```

**Comment by krichtof** [comment]
Oh thank you for your work :)
It works ! I received email with infos about credentials.

Thank you one more time
