### ISSUE TITLE
Matomo 4.1.1 is out

### ISSUE THREAD

**Issue by rysiekpl** [YunoHost-Apps/matomo_ynh#29]
Matomo 4.1.1 is out, but only v.4.0.5 is available via Yunohost.

4.1.1-related changes seems to have been merged into a separate branch (`4.1.1`) but it is not clear what's blocking it from being merged into master?

**Comment by ericgaspar** [comment]
Upgrading to 4.1.1 seems to deactivate the GeoIP plugin ... This problem will probably get fixed with the 4.2 version.

**Comment by rysiekpl** [comment]
Closing, since 4.2.0 got the Yunohost treatment now. Weee!
