### ISSUE TITLE
Is it possible to find the mysql information from CLI?

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/matomo_ynh#40]
My internet provider won't allow the use of port 25 for email—can I find the mysql information elsewhere?

**Comment by ericgaspar** [comment]
Database credentials are in this file `/var/www/matomo/config/config.ini.php`

**Comment by lenowac** [comment]
that file is non existent. is there a sample config for the yh version available?

**Comment by amanahuja** [comment]
I think OP was looking for the myql information that was requested during the admin setup after install, at which point they wouldn't be a `config.ini.php` file. 

@brimwats1 I was in the same position, and resolved the problem by resetting the user password using the MySQL command line. 

```
mysql> SET PASSWORD FOR 'matomo'@'localhost' = PASSWORD('some_new_password');
```
Easy to google for more information, e.g. https://linuxize.com/post/how-to-change-mysql-user-password/

You can then enter the database connection information required during the admin setup.
