### ISSUE TITLE
upgrade script: variable phpversion not set

### ISSUE THREAD

**Issue by h3ndrik** [YunoHost-Apps/matomo_ynh#84]
when updating matomo from _4.10.1~ynh2_ to _4.11.0~ynh2_ i get the following error:

```
Warnung: ./upgrade: Zeile 117: phpversion ist nicht gesetzt.
Warnung: [Error] Upgrade failed.
```

and then the updater reverts back to the backed-up version.
fyi: i'm still on buster. have matomo installed for quite a while.

**Comment by tituspijean** [comment]
Closed by #83
