### ISSUE TITLE
cron error

### ISSUE THREAD

**Issue by jimlunsford** [YunoHost-Apps/matomo_ynh#9]
I am getting the following cron error. Can you advise how to fix?

ERROR [2019-10-12 05:05:06] 20964  Got invalid response from API request: ?module=API&method=API.get&idSite=1&period=day&date=last2&format=php&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of 'memory_limit' in your php.ini file.  For more information and the error message please check your web server's error Log file. As this core:archive command triggers PHP processes over HTTP, you can find the error message in your Matomo's web server error logs.
ERROR [2019-10-12 05:05:06] 20964  Empty or invalid response '' for website id 1, Time elapsed: 3.761s, skipping
ERROR [2019-10-12 05:05:14] 20964  Got invalid response from API request: ?module=API&method=API.get&idSite=2&period=day&date=last2&format=php&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of 'memory_limit' in your php.ini file.  For more information and the error message please check your web server's error Log file. As this core:archive command triggers PHP processes over HTTP, you can find the error message in your Matomo's web server error logs.
ERROR [2019-10-12 05:05:14] 20964  Empty or invalid response '' for website id 2, Time elapsed: 3.098s, skipping
ERROR [2019-10-12 05:05:21] 20964  Got invalid response from API request: ?module=API&method=API.get&idSite=3&period=day&date=last2&format=php&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of 'memory_limit' in your php.ini file.  For more information and the error message please check your web server's error Log file. As this core:archive command triggers PHP processes over HTTP, you can find the error message in your Matomo's web server error logs.
ERROR [2019-10-12 05:05:21] 20964  Empty or invalid response '' for website id 3, Time elapsed: 2.794s, skipping
ERROR [2019-10-12 05:05:29] 20964  Got invalid response from API request: ?module=API&method=API.get&idSite=4&period=day&date=last2&format=php&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of 'memory_limit' in your php.ini file.  For more information and the error message please check your web server's error Log file. As this core:archive command triggers PHP processes over HTTP, you can find the error message in your Matomo's web server error logs.
ERROR [2019-10-12 05:05:29] 20964  Empty or invalid response '' for website id 4, Time elapsed: 3.306s, skipping
ERROR [2019-10-12 05:05:36] 20964  Got invalid response from API request: ?module=API&method=API.get&idSite=5&period=day&date=last2&format=php&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of 'memory_limit' in your php.ini file.  For more information and the error message please check your web server's error Log file. As this core:archive command triggers PHP processes over HTTP, you can find the error message in your Matomo's web server error logs.
ERROR [2019-10-12 05:05:36] 20964  Empty or invalid response '' for website id 5, Time elapsed: 2.892s, skipping

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 39845888) (tried to allocate 23068704 bytes) in /var/www/matomo/vendor/pear/archive_tar/Archive/Tar.php on line 1864

**Comment by Findus23** [comment]
Hi, 

The error is pretty much what it says: The PHP script uses 39 MB which seems to be more than your PHP memory limit allows (or is available on your server).

I'd recommend you to increase the memory limit as 40MB is really little when downloading files (as in this case) or archiving a lot of data.

**Comment by jimlunsford** [comment]
Do I change this in the php.ini file? If so where is it located? I have tried to look for it with no success.

**Comment by ericgaspar** [comment]
Testing #24 should solve this problem. `memory_limit` is now set to 256M

**Comment by ericgaspar** [comment]
should be fixed with #24
